name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
      
  schedule:
    - cron: '20 17 * * *'
    
jobs:
  call-semgrep:
    uses: cloudflare/advisories/.github/workflows/semgrep.yml@main
    secrets: inherit
